#! /usr/bin/env bash

set -euf -o pipefail

if [ "$#" -ne 1 ]; then
    echo "Usage: bild [debug | release | hfile ]"
    exit 1
fi



cflags_global="-std=c99 -Wall -g -Wno-format-extra-args"
cflags_release="$cflags_global -O3 -DNDEBUG"
cflags_debug="$cflags_global -Werror -pedantic"
CC=clang

deps="example.c debug.c influx-writer.c inih/ini.c"
out="example"

if [ "$1" = "hfile" ]; then
    cat debug.h influx-writer.h debug.c influx-writer.c > influx-writer-headeronly.h
    set -x
    $CC -o influx-writer-headeronly.test $cflags_release influx-writer-headeronly.h
    rm influx-writer-headeronly.test
    exit 0 
fi


if [ "$1" = "debug" ]; then
    flags=$cflags_debug
else
    flags=$cflags_release
fi

set -x
$CC -o $out $deps $flags
